# Properties active for ALL profiles:
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}



# Depending on which profile is active, the application gives
# itself a different name when registering with Eureka
---
spring:
  profiles: subject
  application:
    name: subject
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
words: I,You,He,She,It
server:
  port: ${PORT:${SERVER_PORT:0}}
  
---
spring:
  profiles: verb
  application:
    name: verb
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
words: ran,knew,had,saw,bought
server:
  port: ${PORT:${SERVER_PORT:0}}
---
spring:
  profiles: article
  application:
    name: article
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
words: a,the
server:
  port: ${PORT:${SERVER_PORT:0}}
---
spring:
  profiles: adjective
  application:
    name: adjective
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
words: reasonable,leaky,suspicious,ordinary,unlikely
server:
  port: ${PORT:${SERVER_PORT:0}}
---
spring:
  profiles: noun
  application:
    name: noun
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
words: boat,book,vote,seat,backpack,partition,groundhog
server:
  port: ${PORT:${SERVER_PORT:0}}